language: go
go:
  - 1.8
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make install get-tools
before_script:
  - make fmt vet lint
script:
  - make test
